#.github/workflows/flutter.yml
name: Flutter CI

on:
  push:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          
      - run: flutter --version
        
      - name: Install dependencies
        run: flutter pub get

      - name: Deploy
        run: flutter build web

      - name: S3 Upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            ./build/web \
            s3://sury-gs25-pos